import {ASSET_CATEGORIES, MARKET_TYPES} from '../asset-categories.js';

/* Curated commodity suggestions feed prefs search and sensible default metadata for weekday-session commodities. */
const COMMODITY_TICKER_DEFINITIONS = [
    {
        label: 'BAR',
        symbol: 'bar.us',
        priceDecimals: 2,
        keywords: ['gold bullion', 'physical gold'],
    },
    {
        label: 'BCI',
        symbol: 'bci.us',
        priceDecimals: 2,
        keywords: ['broad commodities', 'commodity index'],
    },
    {
        label: 'BNO',
        symbol: 'bno.us',
        priceDecimals: 2,
        keywords: ['brent oil', 'oil etf'],
    },
    {
        label: 'BOIL',
        symbol: 'boil.us',
        priceDecimals: 2,
        keywords: ['leveraged natural gas', 'natural gas etf'],
    },
    {
        label: 'CANE',
        symbol: 'cane.us',
        priceDecimals: 2,
        keywords: ['sugar fund', 'sugar etf'],
    },
    {
        label: 'CMDY',
        symbol: 'cmdy.us',
        priceDecimals: 2,
        keywords: ['commodity strategy', 'broad commodities'],
    },
    {
        label: 'COM',
        symbol: 'com.us',
        priceDecimals: 2,
        keywords: ['commodity index', 'broad commodities'],
    },
    {
        label: 'COMT',
        symbol: 'comt.us',
        priceDecimals: 2,
        keywords: ['commodity total return', 'broad commodities'],
    },
    {
        label: 'COPX',
        symbol: 'copx.us',
        priceDecimals: 2,
        keywords: ['copper miners', 'mining'],
    },
    {
        label: 'CORN',
        symbol: 'corn.us',
        priceDecimals: 2,
        keywords: ['corn fund', 'agriculture'],
    },
    {
        label: 'COWS',
        symbol: 'cows.us',
        priceDecimals: 2,
        keywords: ['livestock fund', 'agriculture'],
    },
    {
        label: 'CPER',
        symbol: 'cper.us',
        priceDecimals: 2,
        keywords: ['copper etf', 'copper'],
    },
    {
        label: 'CUT',
        symbol: 'cut.us',
        priceDecimals: 2,
        keywords: ['timber forestry', 'wood'],
    },
    {
        label: 'Cocoa',
        symbol: 'cc.f',
        priceDecimals: 2,
        keywords: ['cocoa futures'],
    },
    {
        label: 'Coffee',
        symbol: 'kc.f',
        priceDecimals: 2,
        keywords: ['coffee futures'],
    },
    {
        label: 'Copper',
        symbol: 'hg.f',
        priceDecimals: 2,
        keywords: ['copper futures'],
    },
    {
        label: 'Corn Futures',
        symbol: 'zc.f',
        priceDecimals: 2,
        keywords: ['corn futures'],
    },
    {
        label: 'Cotton',
        symbol: 'ct.f',
        priceDecimals: 2,
        keywords: ['cotton futures'],
    },
    {
        label: 'Crude Oil Fund',
        symbol: 'dbo.us',
        priceDecimals: 2,
        keywords: ['oil fund', 'crude oil'],
    },
    {
        label: 'DBA',
        symbol: 'dba.us',
        priceDecimals: 2,
        keywords: ['agriculture fund', 'agriculture etf'],
    },
    {
        label: 'DBB',
        symbol: 'dbb.us',
        priceDecimals: 2,
        keywords: ['base metals fund', 'metals etf'],
    },
    {
        label: 'DBC',
        symbol: 'dbc.us',
        priceDecimals: 2,
        keywords: ['commodity index', 'commodities'],
    },
    {
        label: 'DBE',
        symbol: 'dbe.us',
        priceDecimals: 2,
        keywords: ['energy fund', 'energy commodities'],
    },
    {
        label: 'DBP',
        symbol: 'dbp.us',
        priceDecimals: 2,
        keywords: ['precious metals fund', 'precious metals'],
    },
    {
        label: 'DJP',
        symbol: 'djp.us',
        priceDecimals: 2,
        keywords: ['commodity etn', 'broad commodities'],
    },
    {
        label: 'FTGC',
        symbol: 'ftgc.us',
        priceDecimals: 2,
        keywords: ['active commodities', 'commodity strategy'],
    },
    {
        label: 'GC.F',
        symbol: 'gc.f',
        priceDecimals: 2,
        keywords: ['gold futures'],
    },
    {
        label: 'GDX',
        symbol: 'gdx.us',
        priceDecimals: 2,
        keywords: ['gold miners etf', 'gold miners'],
    },
    {
        label: 'GDXJ',
        symbol: 'gdxj.us',
        priceDecimals: 2,
        keywords: ['junior gold miners', 'gold miners'],
    },
    {
        label: 'GF.F',
        symbol: 'gf.f',
        priceDecimals: 2,
        keywords: ['feeder cattle futures', 'livestock'],
    },
    {
        label: 'GLD',
        symbol: 'gld.us',
        priceDecimals: 0,
        keywords: ['gold etf'],
    },
    {
        label: 'GLTR',
        symbol: 'gltr.us',
        priceDecimals: 2,
        keywords: ['precious metals basket', 'multi metal'],
    },
    {
        label: 'GNR',
        symbol: 'gnr.us',
        priceDecimals: 2,
        keywords: ['natural resources', 'resources etf'],
    },
    {
        label: 'GSG',
        symbol: 'gsg.us',
        priceDecimals: 2,
        keywords: ['commodity index', 'broad commodities'],
    },
    {
        label: 'Gasoline',
        symbol: 'rb.f',
        priceDecimals: 2,
        keywords: ['gasoline futures'],
    },
    {
        label: 'HE.F',
        symbol: 'he.f',
        priceDecimals: 2,
        keywords: ['lean hogs futures', 'livestock'],
    },
    {
        label: 'Heating Oil',
        symbol: 'ho.f',
        priceDecimals: 2,
        keywords: ['heating oil futures'],
    },
    {
        label: 'IAU',
        symbol: 'iau.us',
        priceDecimals: 0,
        keywords: ['gold trust etf', 'gold etf'],
    },
    {
        label: 'IYM',
        symbol: 'iym.us',
        priceDecimals: 2,
        keywords: ['basic materials', 'materials etf'],
    },
    {
        label: 'Kansas Wheat',
        symbol: 'ke.f',
        priceDecimals: 2,
        keywords: ['wheat futures', 'kansas wheat'],
    },
    {
        label: 'LB.F',
        symbol: 'lb.f',
        priceDecimals: 2,
        keywords: ['lumber futures', 'lumber'],
    },
    {
        label: 'LE.F',
        symbol: 'le.f',
        priceDecimals: 2,
        keywords: ['live cattle futures', 'livestock'],
    },
    {
        label: 'LIT',
        symbol: 'lit.us',
        priceDecimals: 2,
        keywords: ['lithium', 'battery materials'],
    },
    {
        label: 'METL',
        symbol: 'metl.us',
        priceDecimals: 2,
        keywords: ['metals and mining', 'mining'],
    },
    {
        label: 'MEXX',
        symbol: 'mexx.us',
        priceDecimals: 2,
        keywords: ['metals and miners', 'mining'],
    },
    {
        label: 'MOO',
        symbol: 'moo.us',
        priceDecimals: 2,
        keywords: ['agribusiness', 'agriculture equities'],
    },
    {
        label: 'MXI',
        symbol: 'mxi.us',
        priceDecimals: 2,
        keywords: ['global materials', 'materials etf'],
    },
    {
        label: 'NLR',
        symbol: 'nlr.us',
        priceDecimals: 2,
        keywords: ['nuclear energy', 'uranium'],
    },
    {
        label: 'Natural Gas',
        symbol: 'ng.f',
        priceDecimals: 2,
        keywords: ['nat gas', 'gas futures'],
    },
    {
        label: 'Nickel',
        symbol: 'ni.f',
        priceDecimals: 2,
        keywords: ['nickel futures'],
    },
    {
        label: 'OJ.F',
        symbol: 'oj.f',
        priceDecimals: 2,
        keywords: ['orange juice futures'],
    },
    {
        label: 'PALL',
        symbol: 'pall.us',
        priceDecimals: 2,
        keywords: ['palladium etf', 'palladium'],
    },
    {
        label: 'PDBC',
        symbol: 'pdbc.us',
        priceDecimals: 2,
        keywords: ['commodity strategy', 'broad commodities'],
    },
    {
        label: 'PICK',
        symbol: 'pick.us',
        priceDecimals: 2,
        keywords: ['metals and mining', 'mining'],
    },
    {
        label: 'PPLT',
        symbol: 'pplt.us',
        priceDecimals: 2,
        keywords: ['platinum etf', 'platinum'],
    },
    {
        label: 'PYZ',
        symbol: 'pyz.us',
        priceDecimals: 2,
        keywords: ['materials momentum', 'materials etf'],
    },
    {
        label: 'Palladium',
        symbol: 'pa.f',
        priceDecimals: 2,
        keywords: ['palladium futures'],
    },
    {
        label: 'Platinum',
        symbol: 'pl.f',
        priceDecimals: 2,
        keywords: ['platinum futures'],
    },
    {
        label: 'REMX',
        symbol: 'remx.us',
        priceDecimals: 2,
        keywords: ['rare earth miners', 'rare earths'],
    },
    {
        label: 'SB.F',
        symbol: 'sb.f',
        priceDecimals: 2,
        keywords: ['sugar futures'],
    },
    {
        label: 'SGOL',
        symbol: 'sgol.us',
        priceDecimals: 0,
        keywords: ['gold trust', 'gold etf'],
    },
    {
        label: 'SI.F',
        symbol: 'si.f',
        priceDecimals: 2,
        keywords: ['silver futures'],
    },
    {
        label: 'SIL',
        symbol: 'sil.us',
        priceDecimals: 2,
        keywords: ['silver miners', 'silver miners'],
    },
    {
        label: 'SILJ',
        symbol: 'silj.us',
        priceDecimals: 2,
        keywords: ['junior silver miners', 'silver miners'],
    },
    {
        label: 'SLV',
        symbol: 'slv.us',
        priceDecimals: 2,
        keywords: ['silver etf'],
    },
    {
        label: 'SOYB',
        symbol: 'soyb.us',
        priceDecimals: 2,
        keywords: ['soybean fund', 'agriculture'],
    },
    {
        label: 'Silver',
        symbol: 'xagusd',
        priceDecimals: 2,
        keywords: ['xag', 'spot silver'],
    },
    {
        label: 'Soybean Meal',
        symbol: 'zm.f',
        priceDecimals: 2,
        keywords: ['soybean meal futures'],
    },
    {
        label: 'Soybean Oil',
        symbol: 'zl.f',
        priceDecimals: 2,
        keywords: ['soybean oil futures'],
    },
    {
        label: 'Soybeans',
        symbol: 'zs.f',
        priceDecimals: 2,
        keywords: ['soybean futures'],
    },
    {
        label: 'TAN',
        symbol: 'tan.us',
        priceDecimals: 2,
        keywords: ['solar materials', 'clean energy'],
    },
    {
        label: 'UCO',
        symbol: 'uco.us',
        priceDecimals: 2,
        keywords: ['leveraged crude oil', 'oil etf'],
    },
    {
        label: 'UGA',
        symbol: 'uga.us',
        priceDecimals: 2,
        keywords: ['gasoline fund', 'gasoline etf'],
    },
    {
        label: 'UNG',
        symbol: 'ung.us',
        priceDecimals: 2,
        keywords: ['natural gas etf', 'gas etf'],
    },
    {
        label: 'UNL',
        symbol: 'unl.us',
        priceDecimals: 2,
        keywords: ['natural gas long', 'natural gas curve'],
    },
    {
        label: 'URA',
        symbol: 'ura.us',
        priceDecimals: 2,
        keywords: ['uranium etf', 'uranium'],
    },
    {
        label: 'URNM',
        symbol: 'urnm.us',
        priceDecimals: 2,
        keywords: ['uranium miners', 'uranium'],
    },
    {
        label: 'USCI',
        symbol: 'usci.us',
        priceDecimals: 2,
        keywords: ['commodity index', 'commodity strategy'],
    },
    {
        label: 'USL',
        symbol: 'usl.us',
        priceDecimals: 2,
        keywords: ['12 month oil', 'oil etf'],
    },
    {
        label: 'USO',
        symbol: 'uso.us',
        priceDecimals: 2,
        keywords: ['oil etf', 'crude oil'],
    },
    {
        label: 'VDE',
        symbol: 'vde.us',
        priceDecimals: 2,
        keywords: ['energy etf', 'energy sector'],
    },
    {
        label: 'WEAT',
        symbol: 'weat.us',
        priceDecimals: 2,
        keywords: ['wheat fund', 'agriculture'],
    },
    {
        label: 'WOOD',
        symbol: 'wood.us',
        priceDecimals: 2,
        keywords: ['timber', 'wood equities'],
    },
    {
        label: 'Wheat',
        symbol: 'zw.f',
        priceDecimals: 2,
        keywords: ['wheat futures'],
    },
    {
        label: 'XES',
        symbol: 'xes.us',
        priceDecimals: 2,
        keywords: ['oil services', 'energy services'],
    },
    {
        label: 'XLB',
        symbol: 'xlb.us',
        priceDecimals: 2,
        keywords: ['materials sector', 'materials etf'],
    },
    {
        label: 'XME',
        symbol: 'xme.us',
        priceDecimals: 2,
        keywords: ['metals mining', 'miners etf'],
    },
    {
        label: 'XOP',
        symbol: 'xop.us',
        priceDecimals: 2,
        keywords: ['oil gas explorers', 'energy exploration'],
    },
    {
        label: 'Zinc',
        symbol: 'zn.f',
        priceDecimals: 2,
        keywords: ['zinc futures'],
    },
];

export const COMMODITY_TICKERS = COMMODITY_TICKER_DEFINITIONS.map(entry => ({
    assetCategory: ASSET_CATEGORIES.COMMODITY,
    label: entry.label,
    symbol: entry.symbol,
    priceDecimals: entry.priceDecimals,
    marketType: MARKET_TYPES.WEEKDAY_SESSION,
    keywords: [...entry.keywords],
}));
