import {ASSET_CATEGORIES, MARKET_TYPES} from '../asset-categories.js';

/* Curated FX suggestions give prefs a searchable baseline for common weekday currency markets. */
export const FX_TICKERS = [
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'AUD/USD',
        symbol: 'audusd',
        priceDecimals: 4,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['aussie'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'DXY',
        symbol: 'dx.f',
        priceDecimals: 2,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['dollar index', 'usd index'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'EUR/GBP',
        symbol: 'eurgbp',
        priceDecimals: 4,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['euro sterling'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'EUR/JPY',
        symbol: 'eurjpy',
        priceDecimals: 2,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['euro yen'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'EUR/USD',
        symbol: 'eurusd',
        priceDecimals: 4,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['euro dollar', 'eurusd'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'GBP/USD',
        symbol: 'gbpusd',
        priceDecimals: 4,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['cable', 'sterling'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'NZD/USD',
        symbol: 'nzdusd',
        priceDecimals: 4,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['kiwi'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'USD/CAD',
        symbol: 'usdcad',
        priceDecimals: 4,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['canadian dollar', 'loonie'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'USD/CHF',
        symbol: 'usdchf',
        priceDecimals: 4,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['swiss franc'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'USD/JPY',
        symbol: 'usdjpy',
        priceDecimals: 2,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['yen'],
    },
    {
        assetCategory: ASSET_CATEGORIES.FX,
        label: 'USD/SEK',
        symbol: 'usdsek',
        priceDecimals: 4,
        marketType: MARKET_TYPES.WEEKDAY_SESSION,
        keywords: ['swedish krona'],
    },
];
